{% set name = "opentelemetry-proto" %}
{% set version = "1.45.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_proto-{{ version }}.tar.gz
  sha256: 96ee414f24bc3f61ea8e17dc56b4348d4049d73db3eb17c6b3edf75b5b403300

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - protobuf <8.0,>=5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.proto
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-proto
  summary: OpenTelemetry Python Proto
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pb01ka
    - mparry
    - rxm7706
    - mariusvniekerk
